### PR TITLE
Octal example for README

### PR DESCRIPTION
**Pull request by tjcrowder**
Just a simple example to prevent others from making my mistake in #47. (Doh!)

### CODE REVIEW

**Comment by tdd** [comment]
Perhaps an example to isolate file permission bits would be more relatable?

**Comment by tjcrowder** [comment]
@tdd Perhaps. :-) But truthfully I can't see anyone writing `0o6_4_0` rather than `0o640`. I don't think the example needs to be too thoroughly engineered, just present. (It is *slightly* engineered: I used groups of four because a friend who looked into usage of octal told me that seemed to be the usual way they were grouped.)

**Comment by tdd** [comment]
I'm curious how @rwaldron and @samuelgoto feel about this suggested change. They're driving the proposal so I'd defer to them (I don't have merge rights anyway)

**Comment by tjcrowder** [comment]
Just to be clear: I'm not bothered what the example is, just that there be an example. I threw one together for that purpose, but I'm happy to change it as directed by any of you doing the real work here.. :-)

**Review by leobalter — APPROVED** [review]

**Pull request merged**
